### ISSUE TITLE
expected hexadecimal character at line 6, column 14

### ISSUE THREAD

**Issue by Mbr18** [9beach/analyze-sgf#1]
Hi. I want to try analyze.sgf but it returns a "expected hexadecimal character at line 6, column 14" error message. 
See attachments 2x. Tried to Google this error but I am not sure what to do.

[.analyze-sgf.yml.txt](https://github.com/9beach/analyze-sgf/files/6016845/default.analyze-sgf.yml.txt)
[Error_Message.txt](https://github.com/9beach/analyze-sgf/files/6016846/Error_Message.txt)

**Comment by 9beach** [comment]
Modify '\\' to '\\\\', and try again.

  path: "C:\\\\Users\\\\PC\\\\Downloads\\\\test\\\\KG\\\\katago.exe"
  arguments: "analysis -model C:\\\\Users\\\\PC\\\\Downloads\\\\test\\\\KG\\\\kata1-latest.bin.gz -config C:\\\\Users\\\\PC\\\\Downloads\\\\test\\\\KG\\\\analysis_example.cfg"

**Comment by Mbr18** [comment]
Thanks! It works now.
