### ISSUE TITLE
Can I disable name-analyzed.sgf gernerating?

### ISSUE THREAD

**Issue by qcgm1978** [9beach/analyze-sgf#14]
Sometime I only want to save json instead of analyzed.sgf, can I only save json files that would save some time?

**Comment by 9beach** [comment]
We get JSON information while analyzing SGF, so even if we do not save analyzed.sgf, we cannot save any time.

And I'm sorry to tell you that I have no plan to add the option saving only JSON file.

**Comment by qcgm1978** [comment]
I understand.
