### ISSUE TITLE
What does maxVariationsForEachMove mean?

### ISSUE THREAD

**Issue by qcgm1978** [9beach/analyze-sgf#15]
I see there's `maxVariationsForEachMove` option in .analyze-sgf.yml file. What does the variable mean?  I've found "maxVariationsForEachMove" is not a parameter in KataGo. Does the option have effect on the accuracy of predictive win rate?

**Comment by 9beach** [comment]
`maxVariationsForEachMove ` have no effect on the accuracy. KataGo generates so many variations for a move, we can reduce the maximun variations count for a move of a SGF with the option.

**Comment by qcgm1978** [comment]
I understand. Thanks your reply
