### ISSUE TITLE
This file is unreadable error (Sabaki)

### ISSUE THREAD

**Issue by Mbr18** [9beach/analyze-sgf#2]
I downloaded a random game from GoKifu (test b.sgf) and KGS (test a and test c.sgf).

Test b-analyzed and test c-analyzed opens successfully in Sabaki and q5go! 
but
Test a-analyzed cannot be opended in Sabaki (This file is unreadable error) and q5go (Erros found in SGF file).
I think because Test a is a unfinished game?

Attachments:
[test.zip](https://github.com/9beach/analyze-sgf/files/6017865/test.zip)

And a extra question. How do i update analyze.sgf? And how do I check if there is an update?

Thank you in advance!

**Comment by 9beach** [comment]
I will check those files soon.

Try `npm outdate -g`, you can check if `analyze-sgf` is outdated, and if so, simply type again `npm install -g analyze-sgf`.

**Comment by 9beach** [comment]
Fixed (63f5c8e). That was a bug.

Please update with `npm install -g analyze-sgf`, and try again.

Thank you!

**Comment by Mbr18** [comment]
The bug is fixed! 
With the new version the analyzed version of test c (not test a) opens now in Sabaki and q5go.
