### ISSUE TITLE
Feature request: Swap "proposed variations"

### ISSUE THREAD

**Issue by Mbr18** [9beach/analyze-sgf#3]
I would like to swap the "proposed varations" text with "Bad moves left" in the analyzed SGF file.
Or a option to remove "proposed varations"? 

Because on my mobile phone the room for text is limited and I think the "Bad moves left" information is more interesting for me.
Thank you in advance.

**Comment by 9beach** [comment]
I think it's a reasonable request. I changed the position of proposed variations to the bottom of the comment. Please update and try again.

Notice that the sequence of the variation is automatically played if you hover your mouse over a proposed variation in Sabaki.

**Comment by Mbr18** [comment]
Thanks! 

_Notice that the sequence of the variation is automatically played if you hover your mouse over a proposed variation in Sabaki._
That is a nice feature!
