### ISSUE TITLE
Does not handle SGF with handicap correctly

### ISSUE THREAD

**Issue by Mbr18** [9beach/analyze-sgf#4]
Please check moves C16  "Analyze-SGF_1337206 (3200v)". 

For example:
-Move 149 (a variant of move 149: C15 C14 .. C9 B18)
-Move 155 (a variant of move 155: C15 C14 .. A8 G8)

Conclusion: 
Analyze-sgf does not recognize the stone at C16 (which is the first move). So for example the variants of move 149 and move 155 places two stones on C16. With the analyze of q5go (q5go_Kata_1337206.sgf) this error does not seem to happen.

Attachement:
1x

[SGF060321.zip](https://github.com/9beach/analyze-sgf/files/6096163/SGF060321.zip)

**Comment by 9beach** [comment]
Thank you. You were right! Please update (`npm install -g analyze-sgf`) and try again.

**Comment by Mbr18** [comment]
Bug is fixed!
