### ISSUE TITLE
Does not handle SGF with pass moves

### ISSUE THREAD

**Issue by Mbr18** [9beach/analyze-sgf#5]
The first 17 moves contains "pass" moves which (maybe) causes the following error:
**, while processing: e9.sgfboard location: U20","field":"moves","id":"9beach-1615326819529"}**
Due to this error the analyze is halted.

Attached SGF:
[e9.zip](https://github.com/9beach/analyze-sgf/files/6111667/e9.zip)

**Comment by 9beach** [comment]
Thank you again!
