### ISSUE TITLE
Error when analysing multiple SGF

### ISSUE THREAD

**Issue by Mbr18** [9beach/analyze-sgf#7]
**A) four SGF's:**  
"analyze-sgf 01.sgf 02.sgf 03.sgf 04.sgf" 
works.

**B) five SGF's:** 
"analyze-sgf 01.sgf 02.sgf 03.sgf 04.sgf 05.sgf" 
crashes with the following error:

0% (0/136, 800 visits) | ETA: 0s (11s)
Process error. Please fix: C:\Users\m\.analyze-sgf.yml
{"path":"C:\\Users\\m\\Desktop\\Engines\\KG\\katago.exe","arguments":"analysis -model C:\\Users\\m\\Desktop\\Engines\\KG\\kata1-latest.bin.gz -config C:\\Users\\m\\Desktop\\Engines\\KG\\analysis_example.cfg"}

Attachment:
[Test180321.zip](https://github.com/9beach/analyze-sgf/files/6164235/Test180321.zip)

**Comment by 9beach** [comment]
Thank you! Please update and try again.

**Comment by Mbr18** [comment]
Works now! Bug is fixed.

**Comment by qcgm1978** [comment]
Can I specify a folder to analyze? e.g. `analyze-sgf -s /Users/user/Documents/data/resource/go/李轩豪`

**Comment by apetresc** [comment]
@qcgm1978 I don't think so, but you can specify multiple SGF files, so if you're using a shell that supports wildcard expansion (i.e most of them), you should be able to just do `analyze-sgf -s /Users/user/Documents/data/resource/go/李轩豪/*.sgf`.

**Comment by qcgm1978** [comment]
> @qcgm1978 I don't think so, but you can specify multiple SGF files, so if you're using a shell that supports wildcard expansion (i.e most of them), you should be able to just do `analyze-sgf -s /Users/user/Documents/data/resource/go/李轩豪/*.sgf`.

There is a problem with this. After analyzing the sgf file, the new analyzed file will continue to be considered as a file to be analyzed in the folder, causing a dead loop and the analysis will not end.

**Comment by apetresc** [comment]
No, that shouldn't happen; the shell evaluates the wildcard at the time the command is being constructed. Once the process is invoked, the list is fixed and won't change to include the newly-created files until the next time you run the command and expand a new wildcard.

**Comment by qcgm1978** [comment]
Ok, I'll try it again. Thanks your answer.

Update: Yes it works.

**Comment by apetresc** [comment]
Glad to hear it :)
